/**
 * Catálogo canônico de Permissões e Perfis do Procedi.
 * Alinhado 1:1 com o backend Java (PermissaoCodigos.java, PerfilAcessoCodigos.java)
 * e com as migrations Flyway (V155__refactor_canonico_tb_permissao.sql).
 */

// ── 8 Módulos Canônicos do Sistema ───────────────────────────────────────────
export const MODULOS_SISTEMA = Object.freeze({
  AGENDA: 'Agenda',
  PACIENTES: 'Pacientes',
  GALERIA: 'Galeria',
  ANAMNESE: 'Anamnese',
  PRONTUARIO: 'Prontuário',
  DOCUMENTOS: 'Documentos',
  CATALOGO: 'Catálogo',
  CLINICA: 'Clínica',
  EQUIPE: 'Equipe',
  SISTEMA: 'Sistema',
});

// ── 43 Permissões Canônicas Ativas ───────────────────────────────────────────
export const PERMISSOES = Object.freeze({
  // 1. Módulo Agenda (10)
  AGENDA_VER: 'AGENDA_VER',
  AGENDA_CRIAR: 'AGENDA_CRIAR',
  AGENDA_EDITAR: 'AGENDA_EDITAR',
  AGENDA_EXCLUIR: 'AGENDA_EXCLUIR',
  AGENDA_BLOQUEIO_GERENCIAR: 'AGENDA_BLOQUEIO_GERENCIAR',
  CONFIRMACAO_GERENCIAR: 'CONFIRMACAO_GERENCIAR',
  AGENDA_MULTI_VER: 'AGENDA_MULTI_VER',
  AGENDA_PROPRIA_VER: 'AGENDA_PROPRIA_VER',
  AGENDA_FORA_DISP_ENCAIXAR: 'AGENDA_FORA_DISP_ENCAIXAR',
  AGENDA_APARECER: 'AGENDA_APARECER',

  // 2. Módulo Pacientes (4)
  PACIENTE_VER: 'PACIENTE_VER',
  PACIENTE_CRIAR: 'PACIENTE_CRIAR',
  PACIENTE_EDITAR: 'PACIENTE_EDITAR',
  PACIENTE_EXCLUIR: 'PACIENTE_EXCLUIR',

  // 3. Módulo Galeria (1)
  PACIENTE_GALERIA_VER: 'PACIENTE_GALERIA_VER',

  // 4. Módulo Anamnese (5)
  ANAMNESE_PREENCHIMENTO_VER: 'ANAMNESE_PREENCHIMENTO_VER',
  ANAMNESE_PREENCHIMENTO_CRIAR: 'ANAMNESE_PREENCHIMENTO_CRIAR',
  ANAMNESE_MODELO_VER: 'ANAMNESE_MODELO_VER',
  ANAMNESE_MODELO_EDITAR: 'ANAMNESE_MODELO_EDITAR',
  HUB_ANAMNESE_VER: 'HUB_ANAMNESE_VER',

  // 5. Módulo Prontuário (10)
  PRONTUARIO_VER: 'PRONTUARIO_VER',
  PRONTUARIO_CRIAR: 'PRONTUARIO_CRIAR',
  PACIENTE_NOTA_VER: 'PACIENTE_NOTA_VER',
  PACIENTE_NOTA_CRIAR: 'PACIENTE_NOTA_CRIAR',
  PACIENTE_NOTA_EDITAR: 'PACIENTE_NOTA_EDITAR',
  EVOLUCAO_GERENCIAR: 'EVOLUCAO_GERENCIAR',
  ORIENTACAO_GERENCIAR: 'ORIENTACAO_GERENCIAR',
  HUB_AVALIACAO_VER: 'HUB_AVALIACAO_VER',
  HUB_PROCEDIMENTO_EXECUTAR: 'HUB_PROCEDIMENTO_EXECUTAR',
  HUB_ORIENTACAO_VER: 'HUB_ORIENTACAO_VER',

  // 6. Módulo Documentos (5)
  PACIENTE_DOCUMENTO_VER: 'PACIENTE_DOCUMENTO_VER',
  DOCUMENTO_ASSINATURA_CRIAR: 'DOCUMENTO_ASSINATURA_CRIAR',
  DOC_MODELO_VER: 'DOC_MODELO_VER',
  DOC_MODELO_EDITAR: 'DOC_MODELO_EDITAR',
  HUB_TERMOS_VER: 'HUB_TERMOS_VER',

  // 7. Módulo Catálogo (5)
  CATALOGO_VER: 'CATALOGO_VER',
  CATALOGO_EDITAR: 'CATALOGO_EDITAR',
  PRECOS_EDITAR: 'PRECOS_EDITAR',
  PACIENTE_ORCAMENTO_VER: 'PACIENTE_ORCAMENTO_VER',
  PACIENTE_ORCAMENTO_EDITAR: 'PACIENTE_ORCAMENTO_EDITAR',

  // 8. Módulo Clínica (3)
  CLINICA_EDITAR: 'CLINICA_EDITAR',
  HORARIO_EDITAR: 'HORARIO_EDITAR',
  FERIADO_EDITAR: 'FERIADO_EDITAR',

  // 9. Módulo Equipe (7)
  USUARIO_VER: 'USUARIO_VER',
  USUARIO_CRIAR: 'USUARIO_CRIAR',
  USUARIO_EDITAR: 'USUARIO_EDITAR',
  USUARIO_EXCLUIR: 'USUARIO_EXCLUIR',
  PERFIL_ACESSO_VER: 'PERFIL_ACESSO_VER',
  PERFIL_ACESSO_EDITAR: 'PERFIL_ACESSO_EDITAR',
  ESPECIALIDADE_GERENCIAR: 'ESPECIALIDADE_GERENCIAR',

  // 10. Módulo Sistema (4)
  AUDITORIA_VER: 'AUDITORIA_VER',
  PDF_EXPORTAR: 'PDF_EXPORTAR',
  NOTIFICACAO_VER: 'NOTIFICACAO_VER',
  MSG_TEMPLATE_GERENCIAR: 'MSG_TEMPLATE_GERENCIAR',
});

// ── Perfis Padrão Globais ───────────────────────────────────────────────────
export const PERFIS_ACESSO = Object.freeze({
  DONO: 'DONO',
  ADMINISTRADOR: 'ADMINISTRADOR',
  SOCIO: 'SOCIO',
  PROFISSIONAL_CLINICO: 'PROFISSIONAL_CLINICO',
  MEDICO: 'MEDICO',
  ENFERMEIRO: 'ENFERMEIRO',
  BIOMEDICO: 'BIOMEDICO',
  SECRETARIA: 'SECRETARIA',
  APOIO: 'APOIO',
  // Aliases legados para retrocompatibilidade
  NIVEL_5: 'NIVEL_5',
  NIVEL_4: 'NIVEL_4',
  NIVEL_3: 'NIVEL_3',
  NIVEL_2: 'NIVEL_2',
  NIVEL_1: 'NIVEL_1',
  ADMIN: 'ADMIN',
  PROFISSIONAL: 'PROFISSIONAL',
  RECEPCIONISTA: 'RECEPCIONISTA',
});

// ── Hierarquia de Pesos por Nível ───────────────────────────────────────────
export const PESOS_PERFIL = Object.freeze({
  [PERFIS_ACESSO.DONO]: 100,
  [PERFIS_ACESSO.ADMINISTRADOR]: 50,
  [PERFIS_ACESSO.SOCIO]: 45,
  [PERFIS_ACESSO.PROFISSIONAL_CLINICO]: 40,
  [PERFIS_ACESSO.MEDICO]: 40,
  [PERFIS_ACESSO.ENFERMEIRO]: 35,
  [PERFIS_ACESSO.BIOMEDICO]: 30,
  [PERFIS_ACESSO.SECRETARIA]: 20,
  [PERFIS_ACESSO.APOIO]: 10,
  // Legado
  [PERFIS_ACESSO.NIVEL_5]: 50,
  [PERFIS_ACESSO.NIVEL_4]: 40,
  [PERFIS_ACESSO.NIVEL_3]: 30,
  [PERFIS_ACESSO.NIVEL_2]: 20,
  [PERFIS_ACESSO.NIVEL_1]: 10,
  [PERFIS_ACESSO.ADMIN]: 50,
  [PERFIS_ACESSO.PROFISSIONAL]: 30,
  [PERFIS_ACESSO.RECEPCIONISTA]: 20,
});

const SET_TODAS_PERMISSOES = new Set(Object.values(PERMISSOES));

/**
 * Retorna true se o código é uma permissão canônica ativa válida.
 * @param {string} codigo
 * @returns {boolean}
 */
export const isPermissaoValida = (codigo) => {
  return typeof codigo === 'string' && SET_TODAS_PERMISSOES.has(codigo);
};
