export { ConsultaHub } from './ConsultaHub.jsx';
export { ConsultaModuleHeader } from './ConsultaModuleHeader.jsx';
export { ConsultaEncerrarFooter } from './ConsultaEncerrarFooter.jsx';
export { ConsultaEncerrarConfirmModal } from './ConsultaEncerrarConfirmModal.jsx';
export { CONSULTA_MODULE_LABELS, getEncerrarConsultaMessage } from './consultaModuleLabels.js';
export { ConsultaViewShell } from './ConsultaViewShell.jsx';
export { PlanosTab } from '../planos/PlanosTab.jsx';
export { ConsultaProcedimentoFlow } from './ConsultaProcedimentoFlow.jsx';
export { ConsultaAvaliacaoFlow } from './ConsultaAvaliacaoFlow.jsx';
export { ConsultaRetornoFlow } from './ConsultaRetornoFlow.jsx';
export { ConsultaRetornoOrigemModal } from './ConsultaRetornoOrigemModal.jsx';
export { formatRetornoAvaliacaoTexto } from './consultaRetornoUtils.js';
